### ISSUE TITLE
Figure out if replay delay is done correctly

### ISSUE THREAD

**Issue by Wesmania** [Wesmania/faf-aio-replayserver#3]
Right now we take timestamps at each second to get current streamed replay data position, and we await an appropriate timestamp 5 minutes back when sending it. The legacy replayserver seems to use some timestamped data instead. Figure out if our method is good enough (i.e. prevents cheating by watching an up-to-date replay of a game in progress).
One problem might for example be one player freezing a game for 5 minutes so that a streamed game can progress to a current state. If this is unacceptable, then we'll have to figure something out (depends if the legacy replay server is succeptible as well).

**Comment by norraxx** [comment]
How replay server should behave, if 2 of 4 people will lost connection to another 2 of 4 people? Both teams will send data to the server, but result will be unpredictable.

**Comment by Wesmania** [comment]
AFAIK the legacy replay server does a 'contains' check on old and new data, and that happens to ensure that the data we send comes from one version only. I'd say - use replay data from one player for as long as we can, and if the data ends prematurely, try to match data from another player (with a little overlap to ensure it's the same version) and use that player from then on. If there are no matching players, I don't know what policy would be best.

**Comment by Wesmania** [comment]
A flat 5 minute delay on the data received so far should be enough - we have no timestamping in the protocol anyway without additional parsing, and that would be expensive I think.
