### ISSUE TITLE
Check if we can take advantage of multithreading

### ISSUE THREAD

**Issue by Wesmania** [Wesmania/faf-aio-replayserver#6]
I don't know much about asyncio's interaction with multithreading and whether Python's GIL defeats the purpose anyway. Once we get to the testing phase, it would be good to check if we can get some performance improvements by delegating replays to separate event loops somehow.

**Comment by norraxx** [comment]
IMHO you won't get advantage of multithreading. asyncio gives you the way how to work with network in nonblocking way.
